---

- hosts: server1
  become: yes

#  vars_prompt:
#    - name: folder_name
#      prompt: "Please enter folder_name: "
#      private: no
#      register: folder_name


  tasks:
    - name: create_directory
      file:
        path: "/home/brajcic/{{ folder_name }}"
        state: directory
        mode: '0755'

  post_tasks:
    - name: create_file
      file:
        path: "/home/brajcic/{{ folder_name }}/{{ file_name }}"
        state: touch
        content: |
          This is the first line
          And this is the second line
          Probably third
