---

- hosts: server1
  become: yes

  handlers:
    - name: print
      debug:
        msg: "{{ ansible_facts }}"



  tasks:
    - name: create_dir
      file:
        path: "/home/brajcic/{{ item }}"
        state: directory
      with_items:
        - dir1
        - dir2
        - dir3
      notify: print