---

- hosts: server1
  become: yes

  tasks:

    - name: wait_delay
      wait_for:
        delay: 6
      notify: create_folder

    - name: create_folder
      file:
        path: "/home/brajcic/WaitFolder"
        state: directory