---

- hosts: server1
  become: yes

  handlers:
    - name: delete_folder
      file:
        path: "/home/brajcic/Test"
        state: absent




  tasks:
    - name: create_dir
      file:
        path: "/home/brajcic/{{ item }}"
        state: directory
      with_items:
        - dir1
        - dir2
        - dir3
      notify: delete_folder