---

- hosts: server1
  become: yes

#  vars_prompt:
#    - name: folder_name
#      prompt: "Please enter folder_name: "
#      private: no
#      register: folder_name

  pre_tasks:
    - name: create_directory
      file:
        path: "/home/brajcic/{{ folder_name }}"
        state: directory

    - name: create_file
      copy:
        dest: "/home/brajcic/{{ folder_name }}/{{ file_name }}"
        content: |
          This is the first line
          And this is the second line
          Probably third

  tasks:
    - name: edit_file
      lineinfile:
        dest: "/home/brajcic/{{ folder_name }}/{{ file_name }}"
        regex: "third$"
        line: "Probably third:Bojan"
        state: present


