---

- hosts: server1
  become: yes


  tasks:
    - name: create_dir
      file:
        path: "/home/brajcic/{{ item }}"
        state: directory
      with_items:
        - dir1
        - dir2
        - dir3