---

- hosts: localhost
  connection: local


  tasks:
    - name: Queue build of a project in Jenkins
      uri:
        url: "http://localhost:8080/job/ansible-calls-jenkins//build?token=ansible_token"
        method: POST
        status_code: 201

