---

- hosts: localhost
  connection: local


  tasks:
    - name: Queue build of a project in Jenkins
      uri:
        url: "http://localhost:8080/job/ansible-job-second//build?token=11b4f83aec94f4f1cb599431434a77a364"
        force_basic_auth: yes
        user: "brajcicansible"
        password: "bojan123"
        method: POST
        status_code: 201
        headers:
          Jenkins-Crumb: "80630d71cd5d998e25c5f62ba576f16acf1c593fdab5733fc5f1b38b8422ae29


